
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 15 22:01:08 PDT 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TiposEspeciales = 58;
  public static final int NumeroEntero = 89;
  public static final int Genericos = 35;
  public static final int Incremento = 17;
  public static final int LlaveCerradura = 96;
  public static final int Redes = 49;
  public static final int TipadoDebil = 40;
  public static final int EscrituraPantalla = 60;
  public static final int Vectores = 55;
  public static final int Compilacion = 81;
  public static final int Clases = 24;
  public static final int Git = 83;
  public static final int Punto = 19;
  public static final int Tipodato = 9;
  public static final int VariablesEspeciales = 68;
  public static final int Streams = 42;
  public static final int Decremento = 18;
  public static final int Modificadores = 28;
  public static final int Logs = 74;
  public static final int EspacioNombre = 26;
  public static final int ParentesisApertura = 97;
  public static final int Aserciones = 38;
  public static final int LiteralesEspeciales = 69;
  public static final int Punteros = 34;
  public static final int Archivos = 48;
  public static final int OperacionesMatematicas = 79;
  public static final int LlaveApertura = 95;
  public static final int ERROR = 102;
  public static final int Ciclos = 30;
  public static final int Cadena = 93;
  public static final int OperadoresEspeciales = 13;
  public static final int ParentesisCerradura = 98;
  public static final int Iteradores = 63;
  public static final int Caracter = 92;
  public static final int Constantes = 12;
  public static final int Web = 50;
  public static final int Generadores = 77;
  public static final int Excepciones = 25;
  public static final int OtrosValores = 44;
  public static final int Recursos = 73;
  public static final int Reflexion = 87;
  public static final int Proxies = 86;
  public static final int Metaprogramacion = 43;
  public static final int Sincronizacion = 53;
  public static final int Asignacion = 16;
  public static final int Estados = 66;
  public static final int Opcionales = 62;
  public static final int EnlaceExterno = 94;
  public static final int Require = 33;
  public static final int OtrosReservados = 37;
  public static final int Contrario = 3;
  public static final int Variables = 29;
  public static final int Herencia = 27;
  public static final int Comentarios = 39;
  public static final int ManejoMemoria = 47;
  public static final int FuncionesEspeciales = 56;
  public static final int Pregunta = 2;
  public static final int Relacional = 22;
  public static final int Random = 72;
  public static final int Serializacion = 70;
  public static final int Concurrencia = 36;
  public static final int EOF = 0;
  public static final int Logico = 20;
  public static final int Conceptos = 52;
  public static final int Versiones = 82;
  public static final int CorcheteApertura = 99;
  public static final int Numero = 7;
  public static final int EstructuraCondicional = 67;
  public static final int Condiciones = 31;
  public static final int Conversiones = 64;
  public static final int Acceso = 10;
  public static final int Seguridad = 46;
  public static final int ManejoErrores = 14;
  public static final int Tiempo = 71;
  public static final int Literal = 6;
  public static final int Delimitador = 101;
  public static final int CorcheteCerradura = 100;
  public static final int error = 1;
  public static final int Basededatos = 54;
  public static final int Operaciones = 8;
  public static final int ControlFlujo = 11;
  public static final int CodigosRetorno = 65;
  public static final int Anotaciones = 85;
  public static final int Matrices = 80;
  public static final int SeguridadWeb = 84;
  public static final int Identificador = 5;
  public static final int Contexpr = 51;
  public static final int Reservadas = 15;
  public static final int Enums = 75;
  public static final int NumeroDecimal = 90;
  public static final int Modularizacion = 78;
  public static final int NumerosHexadecimal = 91;
  public static final int Alias = 45;
  public static final int FinalizarPrograma = 61;
  public static final int Funciones = 23;
  public static final int Declaraciones = 76;
  public static final int EstructurasAdicionales = 41;
  public static final int Otros = 59;
  public static final int CiclosEspeciales = 57;
  public static final int E_S = 32;
  public static final int Identificiadores = 88;
  public static final int Comparar = 4;
  public static final int Bits = 21;
}

